# Generated by Django 4.1.2 on 2022-10-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plus_sign',
            name='image_id',
            field=models.IntegerField(default=-1),
        ),
    ]
