# Generated by Django 4.1.2 on 2022-10-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0002_plus_sign_image_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='division_sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ImageField(default=-1, upload_to='')),
                ('image_name', models.CharField(max_length=256)),
                ('image_file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='eight_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ImageField(default=-1, upload_to='')),
                ('image_name', models.CharField(max_length=256)),
                ('image_file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='five_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ImageField(default=-1, upload_to='')),
                ('image_name', models.CharField(max_length=256)),
                ('image_file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='four_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ImageField(default=-1, upload_to='')),
                ('image_name', models.CharField(max_length=256)),
                ('image_file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='minus_sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ImageField(default=-1, upload_to='')),
                ('image_name', models.CharField(max_length=256)),
                ('image_file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='nine_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ImageField(default=-1, upload_to='')),
                ('image_name', models.CharField(max_length=256)),
                ('image_file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='one_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ImageField(default=-1, upload_to='')),
                ('image_name', models.CharField(max_length=256)),
                ('image_file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='seven_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ImageField(default=-1, upload_to='')),
                ('image_name', models.CharField(max_length=256)),
                ('image_file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='six_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ImageField(default=-1, upload_to='')),
                ('image_name', models.CharField(max_length=256)),
                ('image_file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='three_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ImageField(default=-1, upload_to='')),
                ('image_name', models.CharField(max_length=256)),
                ('image_file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='times_sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ImageField(default=-1, upload_to='')),
                ('image_name', models.CharField(max_length=256)),
                ('image_file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='two_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ImageField(default=-1, upload_to='')),
                ('image_name', models.CharField(max_length=256)),
                ('image_file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='zero_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ImageField(default=-1, upload_to='')),
                ('image_name', models.CharField(max_length=256)),
                ('image_file', models.ImageField(upload_to='')),
            ],
        ),
    ]
