# Generated by Django 4.1.2 on 2022-11-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0003_division_sign_eight_number_five_number_four_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division_sign',
            name='image_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='eight_number',
            name='image_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='five_number',
            name='image_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='four_number',
            name='image_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='minus_sign',
            name='image_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='nine_number',
            name='image_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='one_number',
            name='image_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='seven_number',
            name='image_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='six_number',
            name='image_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='three_number',
            name='image_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='times_sign',
            name='image_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='two_number',
            name='image_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='zero_number',
            name='image_id',
            field=models.IntegerField(default=-1),
        ),
    ]
