# Generated by Django 4.1.2 on 2022-11-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0004_alter_division_sign_image_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='meta_data_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(max_length=10)),
                ('number_of_fields', models.IntegerField(default=0)),
            ],
        ),
    ]
